---
framework: mocha
preRun:
     command:
        - npm i
        - npm run  pretest
        - npm run pretest-only
preMerge:
  pattern:
    - "./tests/*.js"
postMerge:
  pattern: 
    - "./tests/*.js"
postRun:
     command:
        - node --version
version: 1.0
configFile: .mocharc.json
