---
framework: mocha
preRun:
     command:
        - npm i
        - npm run  pretest
        - git init
        - ls test_files/
        - rm -rf test_files/
        - git submodule add  https://github.com/SheetJS/test_files
        - npm config set strict-ssl false
        - npm install mocha@2.x voc
        - npm install blanket
        - npm install word
        - npm install coveralls mocha-lcov-reporter
        - npm install jsdom@11.x
preMerge:
  pattern:
    - "./test.js"
postMerge:
  pattern: 
    - "./test.js"
postRun:
     command:
        - node --version
version: 1.0
configFile: .mocharc.json
