---
framework: mocha
preRun:
     command:
        - npm i
        - npm run  pretest
        - git init
        - ls test_files
        - rm -rf test_files/
        - git submodule add  https://github.com/SheetJS/test_files
preMerge:
  pattern:
    - "./tests/*.js"
postMerge:
  pattern: 
    - "./tests/*.js"
postRun:
     command:
        - node --version
version: 1.0
configFile: .mocharc.json
